# Game Boy Connections — Makefile (Plan A)

# Default goal — explicit because Phase 8's codegen rule would otherwise
# steal default-target status from `all:` (Make picks the first concrete
# target it sees, and codegen rules are defined before the ROM target).
.DEFAULT_GOAL := all

# GBDK paths — `lcc` should be on PATH; adjust GBDK_HOME if needed
LCC := lcc

# Compiler / linker flags
# -Wm-yt0x03 → MBC1+RAM+Battery cartridge type byte
# -Wm-yo4    → 4 ROM banks (64KB total)
# -Wm-ya1    → 1 RAM bank (8KB SRAM)
# -Wm-yn"GB" → ROM name in cartridge header
# -Wm-yc     → CGB-compatible cart header (sets byte 0x143 to 0x80).
#              Works on both DMG and GBC. Use -Wm-yC (capital) for
#              GBC-only carts; we want backwards-compat with DMG.
LCC_FLAGS := -Wm-yt0x03 -Wm-yo4 -Wm-ya1 -Wm-yn"GB" -Wm-yc

# Asset conversion (png2asset → C tile data)
# Flags rationale:
#   -spr8x8             : emit 8x8 tiles in row-major order (default -spr8x16
#                         pairs vertically-adjacent cells into 8x16 sprite-tiles
#                         and interleaves them — tile 1 ends up as '0', not '!')
#   -sprite_no_optimize : keep empty + duplicate tiles so tile index matches
#                         (ascii - 0x20). Without this, the all-zero space tile
#                         is deduplicated and every subsequent glyph shifts.
#   -tiles_only         : emit only background tile bytes, no metasprite metadata
#   -keep_palette_order : preserve our DMG-ordered palette (light → dark)
#   -noflip             : disable horizontal/vertical flip optimizations
# Plan C: title.png is no longer in ASSETS_PNG because png2asset's tile-
# emission order for 64×32 images doesn't match its row-major behavior
# on 128×32 (font/font_inv) images. tools/make_title.py now writes
# src/assets_gen/title.{c,h} directly with explicit row-major tile order;
# title.c is checked into git as a generated artifact. Regenerate with
# `python tools/make_title.py` after changing title.png content.
ASSETS_PNG := assets/font.png assets/ui_tiles.png assets/font_inv.png
ASSETS_GEN := $(patsubst assets/%.png,src/assets_gen/%.c,$(ASSETS_PNG))

src/assets_gen/%.c: assets/%.png
	@mkdir -p $(dir $@)
	png2asset $< -o $@ -spr8x8 -bpp 2 -keep_palette_order -sprite_no_optimize -tiles_only -noflip

# Puzzle data codegen — runs whenever JSON or script changes
PUZZLE_JSON := content/puzzles.json
PUZZLE_OUT  := src/puzzles_data.c
PUZZLE_SCRIPT := tools/build_puzzles.py

$(PUZZLE_OUT): $(PUZZLE_JSON) $(PUZZLE_SCRIPT)
	python $(PUZZLE_SCRIPT) $(PUZZLE_JSON) $(PUZZLE_OUT)

# Source files
SRC := src/main.c \
       src/engine/render.c src/engine/input.c src/engine/save.c \
       src/engine/sound.c src/engine/anim.c src/engine/music.c \
       src/game/puzzle_logic.c src/game/layout.c \
       src/game/scene_title.c src/game/scene_play.c src/game/scene_win.c \
       src/game/scene_lose.c src/game/scene_all_done.c \
       src/game/scene_puzzle_select.c \
       src/game/title_theme.c src/game/play_sfx.c \
       src/game/all_done_theme.c
SRC += $(ASSETS_GEN)
SRC += src/assets_gen/title.c       # generated by tools/make_title.py (checked in)
SRC += $(PUZZLE_OUT)
OBJ := $(patsubst src/%.c,build/%.o,$(SRC))

# Output ROM
ROM := build/gameboygame.gb

.PHONY: all clean run size test test-logic test-codegen

all: $(ROM)

# Host-side unit tests: C logic via gcc + Python codegen via unittest
test: test-logic test-codegen

test-logic:
	$(MAKE) -C test

test-codegen:
	cd tools && python -m unittest test_build_puzzles.py

# Build object file from C source.
# Order-only `|` on $(ASSETS_GEN): the generated asset .h files must exist
# before any compilation starts (engine/render.c does #include <font.h>),
# but changes to those .c/.h files don't invalidate every other .o.
build/%.o: src/%.c | $(ASSETS_GEN)
	@mkdir -p $(dir $@)
	$(LCC) $(LCC_FLAGS) -c -o $@ $<

# Link object files into ROM
$(ROM): $(OBJ)
	@mkdir -p $(dir $@)
	$(LCC) $(LCC_FLAGS) -o $@ $(OBJ)

clean:
	rm -rf build/

size: $(ROM)
	@printf "ROM size: %s bytes (max: 65536)\n" "$$(stat -c%s $(ROM) 2>/dev/null || stat -f%z $(ROM))"

run: $(ROM)
	@echo "Open $(ROM) in BGB or SameBoy."
