// AUTO-GENERATED by tools/make_title.py — DO NOT EDIT
#ifndef ASSETS_GEN_TITLE_H
#define ASSETS_GEN_TITLE_H

#include <stdint.h>

#define title_TILE_COUNT 32
extern const uint8_t title_tiles[512];

#endif
