#!/usr/bin/env python3
"""build_puzzles.py — Validate content/puzzles.json and emit src/puzzles_data.c.

Usage: python build_puzzles.py <input_json> <output_c>
"""

import json
import random
import re
import sys
from typing import List, Dict, Any


_NAME_RE = re.compile(r"^[A-Z ]{1,12}$")
_WORD_RE = re.compile(r"^[A-Z]{1,8}$")


# ---- Public validation API ----

def validate_puzzle(puzzle: Dict[str, Any]) -> None:
    """Raise ValueError on validation failure. No return on success."""
    pid = puzzle.get("id", "?")
    cats = puzzle.get("categories", [])

    if len(cats) != 4:
        raise ValueError(f"puzzle {pid}: must have exactly 4 categories, got {len(cats)}")

    tiers = [c.get("tier") for c in cats]
    expected_tiers = {"yellow", "green", "blue", "purple"}
    if set(tiers) != expected_tiers:
        raise ValueError(
            f"puzzle {pid}: tiers must be exactly {expected_tiers}, "
            f"got {set(tiers)} (duplicates or missing)"
        )

    for cat in cats:
        words = cat.get("words", [])
        name = cat.get("name", "")
        tier = cat.get("tier", "?")

        if len(words) != 4:
            raise ValueError(
                f"puzzle {pid}, category {tier!r}: must have exactly 4 words, got {len(words)}"
            )
        if not _NAME_RE.match(name):
            raise ValueError(
                f"puzzle {pid}, category {tier!r}: name {name!r} must match "
                f"^[A-Z ]{{1,12}}$ (uppercase A-Z + space, length 1-12)"
            )
        for w in words:
            if not _WORD_RE.match(w):
                raise ValueError(
                    f"puzzle {pid}, category {tier!r}: word {w!r} must match "
                    f"^[A-Z]{{1,8}}$ (uppercase A-Z only, length 1-8)"
                )

    # Rule 5: no duplicate words (case-insensitive) across the whole puzzle
    all_words = []
    for cat in cats:
        for w in cat["words"]:
            all_words.append(w.upper())
    if len(all_words) != len(set(all_words)):
        seen = set()
        for w in all_words:
            if w in seen:
                raise ValueError(f"puzzle {pid}: duplicate word {w!r}")
            seen.add(w)

    # Rule 6: no category name equals any word (case-insensitive)
    name_set = {cat["name"].upper() for cat in cats}
    word_set = {w for w in all_words}
    collisions = name_set & word_set
    if collisions:
        raise ValueError(
            f"puzzle {pid}: collision between category name and word: {collisions}"
        )


def validate_all(data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Returns the list of non-draft puzzles in input order. Raises on any failure."""
    if "puzzles" not in data or not isinstance(data["puzzles"], list):
        raise ValueError("Top-level must contain 'puzzles' array")
    non_draft = [p for p in data["puzzles"] if not p.get("draft", False)]
    for p in non_draft:
        validate_puzzle(p)
    # Rule 1: ids of non-draft must be 1, 2, 3, ... in order (no gaps)
    for i, p in enumerate(non_draft, start=1):
        if p.get("id") != i:
            raise ValueError(
                f"puzzle at position {i}: id is {p.get('id')!r}, "
                f"expected {i} (ids must be sequential starting from 1, no gaps)"
            )
    return non_draft


# ---- Shuffle (deterministic per puzzle id) ----

def shuffle_puzzle(puzzle_id: int, words_with_groups: List[tuple]) -> List[tuple]:
    """Return a shuffled copy. Same input + same id = same output (deterministic)."""
    rng = random.Random(puzzle_id * 31 + 7)
    shuffled = list(words_with_groups)
    rng.shuffle(shuffled)
    return shuffled


# ---- Codegen ----

def emit_c(puzzles: List[Dict[str, Any]], out_path: str) -> None:
    """Write src/puzzles_data.c with the PUZZLES array and NUM_PUZZLES constant."""
    lines = []
    lines.append("// AUTO-GENERATED by tools/build_puzzles.py — DO NOT EDIT")
    lines.append('#include "game/puzzles_types.h"')
    lines.append("")
    lines.append(f"const uint8_t NUM_PUZZLES = {len(puzzles)};")
    lines.append("")
    lines.append(f"const Puzzle PUZZLES[{len(puzzles)}] = {{")

    tier_order = ["yellow", "green", "blue", "purple"]
    for p in puzzles:
        # Build flat (word, group_idx) list in category-grouped order
        flat = []
        names = ["", "", "", ""]
        for cat in p["categories"]:
            tier_idx = tier_order.index(cat["tier"])
            names[tier_idx] = cat["name"]
            for w in cat["words"]:
                flat.append((w, tier_idx))
        # Shuffle to display order
        shuffled = shuffle_puzzle(p["id"], flat)
        words = [w for w, _ in shuffled]
        groups = [g for _, g in shuffled]

        lines.append(f"  // ----- Puzzle {p['id']} -----")
        lines.append("  {")
        words_c = ", ".join(f'"{w}"' for w in words)
        lines.append(f"    .words = {{ {words_c} }},")
        groups_c = ", ".join(str(g) for g in groups)
        lines.append(f"    .group_of = {{ {groups_c} }},")
        names_c = ", ".join(f'"{n}"' for n in names)
        lines.append(f"    .category_names = {{ {names_c} }}")
        lines.append("  },")
    lines.append("};")

    with open(out_path, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# ---- Main ----

def main(argv: List[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    input_path, output_path = argv[1], argv[2]
    with open(input_path) as f:
        data = json.load(f)
    try:
        puzzles = validate_all(data)
    except ValueError as e:
        print(f"VALIDATION ERROR: {e}", file=sys.stderr)
        return 1
    emit_c(puzzles, output_path)
    print(f"Wrote {len(puzzles)} puzzles to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
