#!/usr/bin/env python3
"""make_title.py — Generate assets/title.png as a small GBCX banner.

Plan C scope: 64×32 pixels = 8×4 tiles = 32 tiles total. Placed at the
top of the TITLE scene via render_set_tile calls in scene_title.c.

Plan B's original 160×144 full-screen design was scrapped — at 360
tiles it didn't fit in VRAM after font + UI + font_inv allocations.
This smaller banner trades full-screen art for a graphical logo while
keeping <12% of the VRAM cost.

Layout: "GB" drawn at 4× scale using the font8x8 glyphs from
make_font.py. Each letter is 32×32 px, two letters = 64 px wide,
exactly fills the banner. (User retitled from "GBCX" → "GB" mid-Plan C
to match the more concise branding.)
"""

import struct
import sys
import zlib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_font import PALETTE, FONT, pack_2bpp_scanline, png_chunk

WIDTH = 64
HEIGHT = 32
SCALE = 4


def _draw_glyph_scaled(px, ch, x0, y0, scale):
    """Draw a font glyph at the given scale into px[y][x]."""
    if ord(ch) < 0x20 or ord(ch) > 0x5F:
        return
    glyph = FONT[ord(ch) - 0x20]
    for r in range(8):
        row_byte = glyph[r]
        for c in range(8):
            if row_byte & (1 << c):
                for dr in range(scale):
                    for dc in range(scale):
                        y = y0 + r * scale + dr
                        x = x0 + c * scale + dc
                        if 0 <= y < HEIGHT and 0 <= x < WIDTH:
                            px[y][x] = 3


def render_pixels():
    px = [[0] * WIDTH for _ in range(HEIGHT)]
    title = "GB"
    for i, ch in enumerate(title):
        _draw_glyph_scaled(px, ch, i * 8 * SCALE, 0, SCALE)
    return px


def write_png(path, pixels):
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", WIDTH, HEIGHT, 2, 3, 0, 0, 0)
    plte = b"".join(struct.pack("BBB", *c) for c in PALETTE)
    raw = bytearray()
    for row in pixels:
        raw.append(0)
        raw.extend(pack_2bpp_scanline(row))
    idat = zlib.compress(bytes(raw), 9)
    body = (
        sig
        + png_chunk(b"IHDR", ihdr)
        + png_chunk(b"PLTE", plte)
        + png_chunk(b"IDAT", idat)
        + png_chunk(b"IEND", b"")
    )
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_bytes(body)


def write_tiles_c(c_path, pixels):
    """Emit title.c with tile bytes in EXPLICIT row-major order.

    png2asset's tile-iteration order for 64×32 images puts tiles in a
    sprite-iteration order we can't easily reverse-engineer (see Plan C
    Phase 2's investigation). Bypass it by writing tile data directly.

    Tile order: tile N at image position (col = N % tiles_wide,
    row = N // tiles_wide), iterating left-to-right then top-to-bottom.
    Each tile is 8x8 pixels = 16 bytes in GB planar 2bpp format:
    8 rows × 2 bytes (plane 0 then plane 1). Within each byte, MSB =
    leftmost pixel (color 0..3 = palette index).
    """
    tiles_wide = WIDTH // 8
    tiles_tall = HEIGHT // 8
    tile_count = tiles_wide * tiles_tall

    tiles_bytes = []
    for ty in range(tiles_tall):
        for tx in range(tiles_wide):
            for r in range(8):
                # Per row, pack 8 pixels into 2 bytes (planes 0 and 1).
                p0 = 0
                p1 = 0
                for c in range(8):
                    px = pixels[ty * 8 + r][tx * 8 + c]
                    bit = 7 - c  # MSB = leftmost
                    if px & 1:
                        p0 |= (1 << bit)
                    if px & 2:
                        p1 |= (1 << bit)
                tiles_bytes.append(p0)
                tiles_bytes.append(p1)

    lines = []
    lines.append("// AUTO-GENERATED by tools/make_title.py — DO NOT EDIT")
    lines.append("// Title banner: %d tiles in explicit row-major order"
                 % tile_count)
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define title_TILE_COUNT %d" % tile_count)
    lines.append("")
    lines.append("const uint8_t title_tiles[%d] = {" % (tile_count * 16))
    for i in range(0, len(tiles_bytes), 16):
        row = ",".join(f"0x{b:02x}" for b in tiles_bytes[i:i+16])
        lines.append("    " + row + ",")
    lines.append("};")
    Path(c_path).parent.mkdir(parents=True, exist_ok=True)
    Path(c_path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_tiles_h(h_path, tile_count):
    lines = []
    lines.append("// AUTO-GENERATED by tools/make_title.py — DO NOT EDIT")
    lines.append("#ifndef ASSETS_GEN_TITLE_H")
    lines.append("#define ASSETS_GEN_TITLE_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define title_TILE_COUNT %d" % tile_count)
    lines.append("extern const uint8_t title_tiles[%d];" % (tile_count * 16))
    lines.append("")
    lines.append("#endif")
    Path(h_path).parent.mkdir(parents=True, exist_ok=True)
    Path(h_path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    # PNG output (for visual debugging / Plan D content swap-in)
    png_path = sys.argv[1] if len(sys.argv) > 1 else "assets/title.png"
    pixels = render_pixels()
    write_png(png_path, pixels)
    tile_count = (WIDTH // 8) * (HEIGHT // 8)
    print(f"Wrote {png_path} ({WIDTH}x{HEIGHT}, {tile_count} tiles)")

    # C output direct — bypasses png2asset's mystery tile ordering
    write_tiles_c("src/assets_gen/title.c", pixels)
    write_tiles_h("src/assets_gen/title.h", tile_count)
    print(f"Wrote src/assets_gen/title.{{c,h}} with explicit row-major tile order")


if __name__ == "__main__":
    main()
